[package]
name = "TLSParse"
version = "0.1.0"
authors = ["jmwample <jack.wampler@colorado.edu>"]
edition = "2018"

[lib]
name = "TLSParse"
crate-type = ["staticlib", "cdylib"]

[dependencies]
pnet = "0.22.0"
pcap = "0.7.0"
